from os import PathLike
from typing import Iterable, Literal, SupportsIndex, TypeAlias
import numpy as np
from numpy.typing import NDArray

_Buffer: TypeAlias = bytes | bytearray | memoryview | NDArray[np.uint8]
_Limits: TypeAlias = Literal["safe", "unlimited"]
__version__: str

def load_numpy(path: str | PathLike[str], color: str = "rgb", dtype: str = "uint8", backend: str = "auto", *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def load_numpy_from_bytes(data: _Buffer, color: str = "rgb", dtype: str = "uint8", backend: str = "auto", *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def load_numpy_simple(path: str | PathLike[str], *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def load_numpy_simple_from_bytes(data: _Buffer, *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def supported_backends() -> tuple[str, ...]: ...

class Loader:
    def __init__(self, paths: Iterable[str | PathLike[str]] | None = None, *, color: str = "rgb", dtype: str = "uint8", backend: str = "auto", limits: _Limits = "safe", max_buffer_bytes: SupportsIndex = 1048576) -> None: ...
    def __call__(self, path: str | PathLike[str]) -> NDArray[np.uint8]: ...
    def __getitem__(self, index: SupportsIndex) -> NDArray[np.uint8]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> Literal[True]: ...
