from os import PathLike
from typing import Literal, TypeAlias
import numpy as np
from numpy.typing import NDArray

_Buffer: TypeAlias = bytes | bytearray | memoryview | NDArray[np.uint8]
_Limits: TypeAlias = Literal["safe", "unlimited"]
__version__: str

def load_numpy(path: str | PathLike[str], color: str = "rgb", dtype: str = "uint8", backend: str = "auto", *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def load_numpy_from_bytes(data: _Buffer, color: str = "rgb", dtype: str = "uint8", backend: str = "auto", *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def load_numpy_simple(path: str | PathLike[str], *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def load_numpy_simple_from_bytes(data: _Buffer, *, limits: _Limits = "safe") -> NDArray[np.uint8]: ...
def supported_backends() -> tuple[str, ...]: ...
